@startuml
title Состояния робота

[*] --> Включено: Подано напряжение
Ожидание: Остановить управление\nПередать состояние на пульт
Включено: Включить двигатель
Выключено: Выключить двигатель.

Режим1: Управление гидравлическими секциями 0, 1, 2, 3 (Стрела).
Режим2: Управление гидравлическими секциями 0, 1, 4, 5 (Стрела)
Режим3: Управление гидравлическими секциями 6, 7, 8, 9 (Платформа)
Режим4: Управление гидравлическими секциями 6, 7, 10, 11 (Платформа)
' Режим5: Включить или выключить свет
' Режим6: Кратковременный гудок

Включено --> Ожидание: Установлено подключение

Ожидание --> Режим1: Пришло сообщение с режимом 1
Ожидание --> Режим2: Пришло сообщение с режимом 2
Ожидание --> Режим3: Пришло сообщение с режимом 3
Ожидание --> Режим4: Пришло сообщение с режимом 4
' Ожидание --> Режим5: Пришло сообщение с режимом 5
' Ожидание --> Режим6: Пришло сообщение с режимом 6
Ожидание --> Выключено: Пришло сообщение с режимом 0
Ожидание --> Выключено: Ошибка
' Ожидание --> Включено: Пришло сообщение с режимом 5

Режим1 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
Режим1 --> Ожидание: Режим недоступен
Режим1 --> Ожидание: Ошибка
Режим1 --> Выключено: Пришло сообщение с режимом 0
Режим1 --> Режим1: Пришло сообщение с режимом 1
Режим1 --> Режим2: Пришло сообщение с режимом 2
Режим1 --> Режим3: Пришло сообщение с режимом 3
Режим1 --> Режим4: Пришло сообщение с режимом 4
' Режим1 --> Режим5: Пришло сообщение с режимом 5
' Режим1 --> Режим6: Пришло сообщение с режимом 6

Режим2 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
Режим2 --> Ожидание: Режим недоступен
Режим2 --> Ожидание: Ошибка
Режим2 --> Выключено: Пришло сообщение с режимом 0
Режим2 --> Режим1: Пришло сообщение с режимом 1
Режим2 --> Режим2: Пришло сообщение с режимом 2
Режим2 --> Режим3: Пришло сообщение с режимом 3
Режим2 --> Режим4: Пришло сообщение с режимом 4
' Режим2 --> Режим5: Пришло сообщение с режимом 5
' Режим2 --> Режим6: Пришло сообщение с режимом 6

Режим3 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
Режим3 --> Ожидание: Режим недоступен
Режим3 --> Ожидание: Ошибка
Режим3 --> Выключено: Пришло сообщение с режимом 0
Режим3 --> Режим1: Пришло сообщение с режимом 1
Режим3 --> Режим2: Пришло сообщение с режимом 2
Режим3 --> Режим3: Пришло сообщение с режимом 3
Режим3 --> Режим4: Пришло сообщение с режимом 4
' Режим3 --> Режим5: Пришло сообщение с режимом 5
' Режим3 --> Режим6: Пришло сообщение с режимом 6

Режим4 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
Режим4 --> Ожидание: Режим недоступен
Режим4 --> Ожидание: Ошибка
Режим4 --> Выключено: Пришло сообщение с режимом 0
Режим4 --> Режим1: Пришло сообщение с режимом 1
Режим4 --> Режим2: Пришло сообщение с режимом 2
Режим4 --> Режим3: Пришло сообщение с режимом 3
Режим4 --> Режим4: Пришло сообщение с режимом 4
' Режим4 --> Режим5: Пришло сообщение с режимом 5
' Режим4 --> Режим6: Пришло сообщение с режимом 6


' Режим5 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
' Режим5 --> Ожидание: Режим недоступен
' Режим5 --> Ожидание: Ошибка
' Режим5 --> Выключено: Пришло сообщение с режимом 0
' Режим5 --> Режим1: Пришло сообщение с режимом 1
' Режим5 --> Режим2: Пришло сообщение с режимом 2
' Режим5 --> Режим3: Пришло сообщение с режимом 3
' Режим5 --> Режим4: Пришло сообщение с режимом 4
' Режим5 --> Режим5: Пришло сообщение с режимом 5
' Режим5 --> Режим6: Пришло сообщение с режимом 6

' Режим6 --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
' Режим6 --> Ожидание: Режим недоступен
' Режим6 --> Ожидание: Ошибка
' Режим6 --> Выключено: Пришло сообщение с режимом 0
' Режим6 --> Режим1: Пришло сообщение с режимом 1
' Режим6 --> Режим2: Пришло сообщение с режимом 2
' Режим6 --> Режим3: Пришло сообщение с режимом 3
' Режим6 --> Режим4: Пришло сообщение с режимом 4
' Режим6 --> Режим5: Пришло сообщение с режимом 5
' Режим6 --> Режим6: Пришло сообщение с режимом 6

Выключено --> Ожидание: прошло > 0.1 сек с прихода последнего сообщения
Выключено --> [*]

@enduml